=== angelmisaeljacome/40260/xml/gramatica.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT tarea (datos, pasos)>
<!ELEMENT datos (materia, profesor, limiteEntrega)>
<!ELEMENT materia (#PCDATA)>
<!ELEMENT profesor (#PCDATA)>
<!ELEMENT limiteEntrega (fecha, hora)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT pasos (objetivo, division, busqueda, borrador, organizacion, revision, entrega)>
<!ELEMENT objetivo (#PCDATA)>
<!ELEMENT division (#PCDATA)>
<!ELEMENT busqueda (#PCDATA)>
<!ELEMENT borrador (#PCDATA)>
<!ELEMENT organizacion (#PCDATA)>
<!ELEMENT revision (#PCDATA)>
<!ELEMENT entrega (#PCDATA)>

=== angelmisaeljacome/40260/xml/gramatica.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tarea SYSTEM "gramatica.dtd">
<tarea>
    <datos>
        <materia>Historia</materia>
        <profesor>Raul Perez</profesor>
        <limiteEntrega>
            <fecha>12/06/2026</fecha>
            <hora>1:00 p.m.</hora>
        </limiteEntrega>
    </datos>
    <pasos>
        <objetivo>Realizar un informe del calentamiento glogal</objetivo>
        <division>Dividir el tema por secciones: introduccion, desarrollo y conclusion</division>
        <busqueda>Buscar informacion en internet y enciclopedias</busqueda>
        <borrador>Realizar una version con todo lo recabado</borrador>
        <organizacion>Seleccionar lo mas importante y reestructurar el formato</organizacion>
        <revision>Verificar se cumpla con las metricas de la tarea</revision>
        <entrega>Entregar la tarea en el medio correspondiente y a tiempo</entrega>
    </pasos>
</tarea>
