=== angelmisaeljacome/40260/xml/xml-00.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT direccion (nombrecompleto correo telefono cumple)>
<!ELEMENT nombrecompleto (nombre apellidos )>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT correo (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT cumple (dia mes anio)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT anio (#PCDATA)>

=== angelmisaeljacome/40260/xml/xml-00.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE direccion SYSTEM "xml-00.dtd">
<direccion>
    <nombrecompleto>
        <nombre>Angel Misael</nombre>
        <apellidos>Jacome Sanchez</apellidos>
    </nombrecompleto>
    <correo>misael@gmail.com</correo>
    <telefono>2635242727</telefono>
    <cumple>
        <dia>1</dia>
        <mes>4</mes>
        <anio>2000</anio>
    <cumple>
</direccion>
